### PR TITLE
fix PHP 8.4 deprecation error (implicitly nullable parameter)

### PR DESCRIPTION
**Pull request by mbolli**
Hope you don't mind another 1.x release ;-)

### CODE REVIEW

**Comment by mbolli** [comment]
@JimTools shameless bump

**Comment by JimTools** [comment]
@mbolli not at all! I’m still supporting V1 as I know it’s widely used but’s highly unlikely I’m going to back port features unless critical.

**Comment by mbolli** [comment]
@JimTools not sure if I understand correctly. do you want to say this is a feature (and therefore won't be merged) or this is providing support and you will merge it because it's still highly used? ;-)

**Comment by JimTools** [comment]
@mbolli sorry for the detail I will merge this I just need to update the ci the also run against 8.4

**Pull request merged**
